### ISSUE TITLE
How portable is the code in cargo-verifier? (was The 'expect' part of 'should_panic' annotation depends on the verifier)

### ISSUE THREAD

**Issue by fshaked** [project-oak/rust-verification-tools#13]
Each verifier has its own way of reporting overflow, for example. This makes the should_panic annotation non-portable.

We could add some mapping in cargo-verify from the strings in the annotation to how each verifier reports them.

If we don't fix this, maybe we should add the verifier name to the annotation?

**Comment by alastairreid** [comment]
I think of cargo-verify as having a shared part and a backend specific part.
(but see at the end for LLVM vs. MIR differences)

## Ignoring LLVM vs MIR

The shared part might need a little conditional code to handle different backends but hopefully not too much.

The backend-specific part (eg all the functions with 'klee' in their name) might need to be completely rewritten for every backend because every verification tool could have a different way of reporting errors.
When porting to a new backend, you probably want to make a copy of all the klee functions, rename them and then hack away at them until you have something that works.
Hopefully, we can then refactor the code a bit to share a bit of code sometimes - but it's probably best to start from the assumption that each backend is independent.

The parts of cargo-verify that look for error messages in the output of a verifier are in that KLEE-specific part
so you should expect to have to completely rewrite it.


## LLVM vs. MIR

At the moment, cargo-verify only supports KLEE which is an LLVM-based verification tool.
Perhaps 50% of the code that is not KLEE-specific is concerned with building LLVM bitcode files.
I think it should be possible to use that code more or less unchanged with any LLVM-based verification tool.

But, MIR-based verification tools don't need to generate LLVM bitcode files and probably have completely different problems.
So maybe the bits concerned with compiling/linking will need to have an LLVM-version and a MIR-version?

**Comment by alastairreid** [comment]
I think this can be closed after the cargo-verify rewrite #90
